"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var square_1 = require("./square");
var obj = new circle_1.circle();
var obj1 = new rectangle_1.rectangle();
var obj2 = new square_1.square();
console.log();
console.log(obj.area());
console.log(obj1.draw());
console.log(obj1.area());
console.log(obj2.draw());
console.log(obj2.area());
