"use strict";
exports.__esModule = true;
var Rectangle_1 = require("./Rectangle");
var Square_1 = require("./Square");
var Circle_1 = require("./Circle");
var r = new Rectangle_1.Rectangle(10, 8);
var s = new Square_1.Square(10);
var c = new Circle_1.Circle(10);
console.log(r.Draw());
console.log(r.Area());
console.log(s.Draw());
console.log(s.Area());
console.log(c.Draw());
console.log(c.Area());
