"use strict";
exports.__esModule = true;
var Rectangle_1 = require("./Rectangle");
var Square_1 = require("./Square");
var Circle_1 = require("./Circle");
var rect = new Rectangle_1.Rectangle(10, 8);
var sq = new Square_1.Square(10);
var cir = new Circle_1.Circle(10);
console.log(rect.Draw());
console.log(rect.Area());
console.log(sq.Draw());
console.log(sq.Area());
console.log(cir.Draw());
console.log(cir.Area());
